### ISSUE TITLE
npm error during "Add @umbraco-cms/backoffice from npm as dev-dependency" step

### ISSUE THREAD

**Issue by stvnhrlnd** [warrenbuckley/Umbraco-Repo-Template#2]
Hi @warrenbuckley,

When I generate a repo from the template I am running into the following error during the **Add @umbraco-cms/backoffice from npm as dev-dependency** step which causes the action to fail:

```console
npm error code 1
npm error path /home/runner/work/Umbraco-Repo-Template/Umbraco-Repo-Template/umbraco.repo.template.client/node_modules/@umbraco-cms/backoffice
npm error command failed
npm error command sh -c npm run generate:tsconfig
npm error > @umbraco-cms/backoffice@14.2.0-rc generate:tsconfig
npm error > node ./devops/tsconfig/index.js
npm error node:internal/modules/cjs/loader:1148
npm error   throw err;
npm error   ^
npm error
npm error Error: Cannot find module '/home/runner/work/Umbraco-Repo-Template/Umbraco-Repo-Template/umbraco.repo.template.client/node_modules/@umbraco-cms/backoffice/devops/tsconfig/index.js'
npm error     at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
npm error     at Module._load (node:internal/modules/cjs/loader:986:27)
npm error     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
npm error     at node:internal/main/run_main_module:28:49 {
npm error   code: 'MODULE_NOT_FOUND',
npm error   requireStack: []
npm error }
npm error
npm error Node.js v20.16.0
npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2024-08-08T19_30_08_598Z-debug-0.log
Error: Process completed with exit code 1.
```

You can see the complete logs here (I tried it a couple of times):

- https://github.com/stvnhrlnd/Umbraco-Repo-Template/actions/runs/10308320619/job/28535469949
- https://github.com/stvnhrlnd/Umbraco-Test-Package/actions/runs/10308356232/job/28535584292

I've not had a chance to look into it properly yet. I can have a look tomorrow but wanted to raise the issue first in case you can spot what it is at a glance.

**Comment by warrenbuckley** [comment]
Hi @stvnhrlnd 
I haven't tried this with `14.2.0-rc` I wonder if something in that has caused it to blow up or something.

I haven't done any package work with 14.2.0-rc directly either

**Comment by warrenbuckley** [comment]
OK I can repro, I just tried upgrading the NPM package to 14.2.0-rc and it bombs, so its an issue with the NPM package that Umbraco has shipped.

```bash
npm error code 1
npm error path C:\Code\some-client-v14\src\SomeClient.Backoffice\node_modules\@umbraco-cms\backoffice
npm error command failed
npm error command C:\Windows\system32\cmd.exe /d /s /c npm run generate:tsconfig
npm error > @umbraco-cms/backoffice@14.2.0-rc generate:tsconfig
npm error > node ./devops/tsconfig/index.js
npm error node:internal/modules/cjs/loader:1148
npm error   throw err;
npm error   ^
npm error
npm error Error: Cannot find module 'C:\Code\some-client-v14\src\SomeClient.Backoffice\node_modules\@umbraco-cms\backoffice\devops\tsconfig\index.js'
npm error     at Module._load (node:internal/modules/cjs/loader:986:27)
npm error     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
npm error     at node:internal/main/run_main_module:28:49 {
npm error   code: 'MODULE_NOT_FOUND',
npm error   requireStack: []
npm error }
npm error
npm error Node.js v20.15.1
```

**Comment by warrenbuckley** [comment]
Raised/reported the issue over on the Umbraco gang's issue tracker 👀 
https://github.com/umbraco/Umbraco-CMS/issues/16892

**Comment by warrenbuckley** [comment]
Looks to be fixed now @stvnhrlnd with Umbraco HQ gang releasing RC2

This was the commit/PR with the fix by HQ to sort out the issue
https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2201

Here is a run that works
https://github.com/warrenbuckley/Is-RC2-Working/actions/runs/10355839128/job/28664373247

Closing this up

**Comment by stvnhrlnd** [comment]
Nice one, thanks @warrenbuckley! #h5yr
